// <auto-generated />
using System;
using Izabella.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Izabella.Migrations
{
    [DbContext(typeof(IzabellaDbContext))]
    [Migration("20260327165206_InitialAll")]
    partial class InitialAll
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Izabella.Models.LiquidManure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cow")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("PregnantHeifer")
                        .HasColumnType("float");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<string>("VoucherIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoucherOut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Young12Preg")
                        .HasColumnType("float");

                    b.Property<double>("Young6_9")
                        .HasColumnType("float");

                    b.Property<double>("Young9_12")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("LiquidManures");
                });

            modelBuilder.Entity("Izabella.Models.LiquidManureSplit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("LiquidManureId")
                        .HasColumnType("int");

                    b.Property<string>("VoucherNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LiquidManureId");

                    b.ToTable("LiquidManureSplits");
                });

            modelBuilder.Entity("Izabella.Models.SolidManure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Calf3_6")
                        .HasColumnType("float");

                    b.Property<double>("CalfMilk")
                        .HasColumnType("float");

                    b.Property<double>("Cow")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Gross")
                        .HasColumnType("float");

                    b.Property<double>("Net")
                        .HasColumnType("float");

                    b.Property<double>("PregnantHeifer")
                        .HasColumnType("float");

                    b.Property<double>("Tare")
                        .HasColumnType("float");

                    b.Property<string>("VoucherIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoucherOut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Young6_9")
                        .HasColumnType("float");

                    b.Property<double>("Young9_12")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SolidManures");
                });

            modelBuilder.Entity("Izabella.Models.SolidManureDaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Calf3_6")
                        .HasColumnType("float");

                    b.Property<double>("CalfMilk")
                        .HasColumnType("float");

                    b.Property<double>("Cow")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("PregnantHeifer")
                        .HasColumnType("float");

                    b.Property<double>("TotalNet")
                        .HasColumnType("float");

                    b.Property<string>("VoucherIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoucherOut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Young6_9")
                        .HasColumnType("float");

                    b.Property<double>("Young9_12")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SolidManureDailies");
                });

            modelBuilder.Entity("Izabella.Models.SolidManureLoad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GrossWeight")
                        .HasColumnType("float");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NetWeight")
                        .HasColumnType("float");

                    b.Property<double>("TareWeight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SolidManureLoads");
                });

            modelBuilder.Entity("Izabella.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Warehouse")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("Izabella.Models.LiquidManureSplit", b =>
                {
                    b.HasOne("Izabella.Models.LiquidManure", "LiquidManure")
                        .WithMany("Splits")
                        .HasForeignKey("LiquidManureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiquidManure");
                });

            modelBuilder.Entity("Izabella.Models.LiquidManure", b =>
                {
                    b.Navigation("Splits");
                });
#pragma warning restore 612, 618
        }
    }
}
